import { login } from "@/server/actions";
import PasswordField from "@/components/PasswordField";

// Login only. Registration was removed at the source: the `signup` server action
// no longer exists, so there is nothing for a crafted POST to call either. New
// accounts are created by an operator from /admin/users, which sets the password
// typed here.
//
// `refCode` is accepted but not rendered. Referral links (`/?ref=CODE`) are still
// generated by the wallet page for players to share, and an operator can attach
// one when provisioning the account — but a self-service form no longer reads it,
// so the parameter is dropped here rather than silently ignored on the server.
export default function AuthForm({ error }: { error?: string }) {
  return (
    <div className="relative mx-auto w-full max-w-md overflow-hidden rounded-3xl border border-amber-300/25 bg-[#1b2a5e]/85 shadow-[0_30px_80px_rgba(0,0,0,0.65),0_0_0_1px_rgba(255,255,255,0.04)_inset] backdrop-blur-xl">
      {/* gold hairline along the top edge */}
      <span className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-amber-300/70 to-transparent" />

      <div className="p-7 sm:p-9">
        <h2 className="text-center text-2xl font-black tracking-tight text-white">
          Welcome back
        </h2>
        <p className="mt-1.5 text-center text-sm text-slate-300/80">
          Sign in to your account to play.
        </p>

        {error && (
          <p
            role="alert"
            className="mt-5 rounded-xl border border-rose-500/40 bg-rose-950/50 px-4 py-2.5 text-sm text-rose-200"
          >
            {error}
          </p>
        )}

        <form action={login} className="mt-6 flex flex-col gap-4">
          <label className="block">
            <span className="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-slate-300">
              Email
            </span>
            <input
              name="email"
              type="email"
              autoComplete="username"
              required
              autoFocus
              placeholder="you@example.com"
              className="w-full rounded-xl border border-white/10 bg-[#0e1a44] px-4 py-3 text-sm text-slate-100 outline-none transition placeholder:text-slate-500 focus:border-sky-400 focus:ring-2 focus:ring-sky-400/25"
            />
          </label>

          <label className="block">
            <span className="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-slate-300">
              Password
            </span>
            <PasswordField
              name="password"
              autoComplete="current-password"
              required
              placeholder="••••••••"
              className="w-full rounded-xl border border-white/10 bg-[#0e1a44] px-4 py-3 text-sm text-slate-100 outline-none transition placeholder:text-slate-500 focus:border-sky-400 focus:ring-2 focus:ring-sky-400/25"
            />
          </label>

          <button
            type="submit"
            className="mt-1 rounded-xl bg-gradient-to-r from-amber-500 via-amber-400 to-yellow-300 px-6 py-3.5 text-sm font-black uppercase tracking-wider text-[#2a1606] shadow-[0_12px_34px_rgba(251,191,36,0.32)] transition hover:brightness-110 active:translate-y-px"
          >
            Enter the vault
          </button>
        </form>

        {/* Still worth telling a prospective player how an account comes to exist,
            but the pointer to /portal is gone: it repeated the "Staff portal" link the
            scene used to carry, and two pointers to the staff login on the player
            sign-in page is one too many. Staff go straight to /portal. */}
        <p className="mt-6 border-t border-white/10 pt-5 text-center text-xs leading-relaxed text-slate-400/85">
          No account yet?{" "}
          <span className="font-semibold text-slate-300">Ask an operator to create one</span>{" "}
          — registration is closed.
        </p>
      </div>
    </div>
  );
}